### ISSUE TITLE
 Arguments imply differing number of rows: 2, 3

### ISSUE THREAD

**Issue by aspardog** [xl0418/ggradar2#13]
Hi!

I get the error in the issue title when I put fullscore = c(1,1,1,1,1,1,1,1) which are are maximum values of the ratio of each variable, the code didn't recognize it. It only recognizes the highest value of the proportion. 

I tried with the last version, and my code ran perfectly.

What should I do to obtain a radar where the points are not the maximum values of each variable but the maximum value of the ratio? That is to say, 1.

Please help.

**Comment by guobinbinbin** [comment]
I get the same problem. When I run the code in the tutorial (https://github.com/xl0418/ggradar2), there is a bug showing below:
fullscore <- c(100,10,300,150,10,10)
a <- ggradar2(dftest,fullscore = fullscore)
Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 31, 30

**Comment by xl0418** [comment]
Bug fixed.
