### ISSUE TITLE
problems with getting a radar graph between 0 and 350%

### ISSUE THREAD

**Issue by alonshepon** [xl0418/ggradar2#14]
Hello!
I am using the following code (see below). The values of all variables are in percentages. I want the radar diagram to go all the way to 350% (highest value) such that the "agroecological"  should be positioned with values of 100% (for all variables) and the two other groups ("conventional", "alternative") should go above or below that 100% based on thier values between 0 and 350. But for some reason it is showing the "conventional" line at 350% (the max circle). I must be doing something wrong, can you please explain to me how to get the right plot?
Thanks
Alon
----- 

LCA_scores <- data.frame(
  row.names = c("conventional", "agroecological","alternative"),
  GHG = c(120,100,80),
  gases = c(250,100,60),
  Marine = c(350,100,60),
  Eutroph = c(100,100,95),
  Terrest = c(300,100,100),
  Acid = c(170,100,100),
  Water = c(350,100,100),
  Land = c(300,100,100),
  Fossil = c(160,100,95))
fullscore1=c(350,350,350,350,350,350,350,350,350)

lcols <- c("#EEA236", "#1AB85C","#FF0000")
pp<-ggradar2(LCA_scores,
         group.colours=lcols,
         fullscore=fullscore1,
         gridline.label = seq(0, 350, 50),
         grid.min = 0, grid.max = 350)+theme(legend.position = "right")

**Comment by guobinbinbin** [comment]
Similar problems

**Comment by xl0418** [comment]
Bug fixed. Pls update the pkg.
