### ISSUE TITLE
Outliers

### ISSUE THREAD

**Issue by alonshepon** [xl0418/ggradar2#15]
Hi,
thank you again for the great radar package!
I have an issue when trying to plot a radar plot with an outlier. In the code below, there is an outlier in one of the variables ("Acid" with a value of 17232), yet I am interested that the radar go from 0 to 500 for all variables since it captures most of the data. The idea is that for this particular point the graph shows two converging lines, whose conversion point is way outside the range of the graph. The rest of the points all reside within 500. Is there a way to do it? I tried changing the fullscore vector and the min and max parameters, but could not see how to do it. I listed the code below.
thank you so much!
Alon

# Demo data
LCA_scores <- data.frame(
  group = c("conventional", "agroecological","alternative"),
  GWP = c(105,100,62),
  Eutroph. = c(302,100,83),
  Acid. = c(17232,100,684),
  Water= c(89,100,100),
  'Depletion' = c(284,100,100),
  'Land' = c(163,100,100),
  'EcoToc.' = c(447,100,100),
  'HumToc.' = c(347,100,100),
  Biodiversity = c(162,100,93))
fullscore1=c(17232,17232,17232,17232,17232,17232,17232,17232,17232)
#

lcols <- c("#EEA236", "#1AB85C","#FF0000")

pp<-ggradar2(LCA_scores,
            group.point.size=3,
            axis.label.size=4,
            fullscore = fullscore1,
            gridline.label = seq(0, 500, 50),
            grid.min = 0,grid.max = 500)+theme(legend.position = c(1.2, 0.3))

pp

**Comment by xl0418** [comment]
Thanks! 

How about using a log scale? Like follows:

library(ggradar2)
library(ggplot2)

LCA_scores <- data.frame(
  group = c("conventional", "agroecological","alternative"),
  GWP = log(c(105,100,62)),
  Eutroph. = log(c(302,100,83)),
  Acid. = log(c(17232,100,684)),
  Water= log(c(89,100,100)),
  'Depletion' = log(c(284,100,100)),
  'Land' = log(c(163,100,100)),
  'EcoToc.' = log(c(447,100,100)),
  'HumToc.' = log(c(347,100,100)),
  Biodiversity = log(c(162,100,93)))
fullscore1=log(c(17232,17232,17232,17232,17232,17232,17232,17232,17232))

lcols <- c("#EEA236", "#1AB85C","#FF0000")

pp<-ggradar2(LCA_scores,
             group.point.size=3,
             axis.label.size=4,
             fullscore = fullscore1,
             gridline.label = seq(0, 500, 50),
             grid.min = 0,grid.max = 500)+theme(legend.position = c(1.2, 0.3))

pp

**Comment by alonshepon** [comment]
thank you for the prompt reply.
It is an option. I have used your advise and used log10, which I think is more intuitive. I modified the code accordingly. I also had to change the min and max and label. See the code below. By the way, the labels show 1 to 4 on the graph but with percentages, how can you remove "%"?
I agree its a good idea, yet because the original values are in percentages I still think it will be hard for the reader to appreciate and make out 200% or differences which are hard to read on a log scale.......Do you have any other options?
Again, many thanks
Alon

LCA_scores <- data.frame(
  group = c("conventional", "agroecological","alternative"),
  GWP = log10(c(105,100,62)),
  Eutroph. = log10(c(302,100,83)),
  Acid. = log10(c(17232,100,684)),
  Water= log10(c(89,100,100)),
  'Depletion' = log10(c(284,100,100)),
  'Land' = log10(c(163,100,100)),
  'EcoToc.' = log10(c(447,100,100)),
  'HumToc.' = log10(c(347,100,100)),
  Biodiversity = log10(c(162,100,93)))
fullscore1=log10(c(17232,17232,17232,17232,17232,17232,17232,17232,17232))


lcols <- c("#EEA236", "#1AB85C","#FF0000")

pp<-ggradar2(LCA_scores,
            group.point.size=3,
            axis.label.size=4,
            fullscore = fullscore1,
            gridline.label = seq(0, log10(17232), 1),
            grid.min = 0,grid.max = log10(17232))+theme(legend.position = c(1.2, 0.3))

pp

**Comment by xl0418** [comment]
To remove the percentage sign, pls use this argument `gridline.label.type = "numeric"`.
As such, you can label the circle axis with the 10^x  scales, which I think the difference would be sufficiently significant. 
Like the code below.


library(ggradar2)
library(ggplot2)

LCA_scores <- data.frame(
  group = c("conventional", "agroecological","alternative"),
  GWP = log10(c(105,100,62)),
  Eutroph. = log10(c(302,100,83)),
  Acid. = log10(c(17232,100,684)),
  Water= log10(c(89,100,100)),
  'Depletion' = log10(c(284,100,100)),
  'Land' = log10(c(163,100,100)),
  'EcoToc.' = log10(c(447,100,100)),
  'HumToc.' = log10(c(347,100,100)),
  Biodiversity = log10(c(162,100,93)))
fullscore1=rep(5, 9)

lcols <- c("#EEA236", "#1AB85C","#FF0000")

pp<-ggradar2(LCA_scores,
             group.point.size=3,
             axis.label.size=4,
             fullscore = fullscore1,
             gridline.label = expression(0,10, 10^2, 10^3, 10^4,10^5),
             grid.min = 0,grid.max = 500,
             gridline.label.type = "numeric")+theme(legend.position = c(1.2, 0.3))

pp

**Comment by alonshepon** [comment]
thank you so much!
I run the code and get the results.....However I do get the following warning message (below). While it does not affect the results, is there a way to suppress it? 
Thanks

Warning messages:
1: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
2: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
3: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
4: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
5: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'
6: In is.na(x) :
  is.na() applied to non-(list or vector) of type 'expression'

**Comment by xl0418** [comment]
Yes, I noticed that. Probably due to the mathematical label on the circle axis. No harm to the figures. I will close this issue. Thanks.
