### ISSUE TITLE
Error with axis.labels

### ISSUE THREAD

**Issue by asierrl** [xl0418/ggradar2#7]
Hi, Liang. 
Thanks a lot for your work improving the options of ggradar. I find especially useful the "sharp" option, which drove me to ggradar2.
I have an issue with axis.labels. Probably I don't understand the proper format they should have. As I come from ggradar I set axis.labels=c("Defense", "Growth", "Reproduction"), but I get the following error message:

 In if (axis.labels == "") { :
  the condition has length > 1 and only the first element will be used

The diagram is plot, anyway, but I don't know if this error has any consequence or what I am doing wrong.
Best regards,
Asier

**Comment by xl0418** [comment]
Hi Asier:

    Thanks for your interest in ggradar2. This is due to that the vector doesn’t fit in the boolean operator, i.e. if axis.labels is a vector, axis.labels == “”  would return a vector of boolean operators. I have fixed this bug. It should be working now. Pls update your package. Thank you for your notice. 
Best,

Liang

---------

Liang Xu
Postdoctoral Research Assistant
Theoretical Plant Community Ecology
Department of Plant Sciences
Oxford University

————
Personal blog
xl0418.github.io

**Comment by asierrl** [comment]
Thanks, Liang. It works smoothly, now.
