### ISSUE TITLE
Format of the legend

### ISSUE THREAD

**Issue by asierrl** [xl0418/ggradar2#8]
It would be nice to control the position of the legend, as well as the vertical spacing among lines. 
Is there a way to do that?
Best regards.
Asier

**Comment by xl0418** [comment]
The generating plot is just of a ggplot class. That means you can customize any theme by adding theme(…). For example, you can add theme(legend.position="left") to the plot you have drawn to put the legend on the left. 

Best,

Liang

---------

Liang Xu
Postdoctoral Research Assistant
Theoretical Plant Community Ecology
Department of Plant Sciences
Oxford University

————
Personal blog
xl0418.github.io
