### ISSUE TITLE
ggradar2 only(not ggradar) - error Summary.factor

### ISSUE THREAD

**Issue by ishtar83** [xl0418/ggradar2#9]
Hi!
ive just started using ggradar2.
I have frequencies (counts) of categorical variables (columns) for 2 individuals (rows)
The plot works fine with ggaradar, but with ggradar2 I get the following error:

"Error in Summary.factor(1:2, na.rm = TRUE) : 
  ‘max’ not meaningful for factors"

Code is below:

head(colorESC_BYoutcome_unf_wide)
# A tibble: 2 x 10
# Groups:   outcome [2]
  outcome    Br Clear  LiBr MotconLight MotgenBr MotgenDark MotgenLiBr MotgenLight  Dark
  <fct>   <int> <int> <int>       <int>    <int>      <int>      <int>       <int> <int>
1 lose        4    27    25           3        5          1         10           3     0
2 win         7     2    14           1       20         10         15           4     5

ggradar2(
  colorESC_BYoutcome_unf_wide, axis.labels = colnames(colorESC_BYoutcome_unf_wide)[-1],
  grid.min = 0, grid.max = 30, group.line.width = 1, 
  group.colours = c("darkturquoise", "coral"),
  group.point.size = 3,axis.label.size = 3,axis.label.offset = 1.1,
  plot.title = "Body patterns at ESCAPE Winner vs Loser - Unfamiliar encounters",
  webtype="lux", base.size=25, radarshape="sharp")

Thanks!
Gabry

**Comment by xl0418** [comment]
It seems that there is something wrong with your data type. The error message "‘max’ not meaningful for factors" means that you are calculating max for factors, which is causing this error. You should change the data type to numberic.
